### ISSUE TITLE
class selectors for howIcanhelp.html

### ISSUE THREAD

**Issue by elmcaleavy** [emmalou11/emmalou11.github.io#1]
Hi John,
This is my issue: I don't know how to change the li and ul properties for howIcanhelp.html I tried making a separate class for them (because our website-wide setting aren't appropriate here), but it doesn't seem to be working out.  Can you look at howicanhelp.html and also at style.css to see why it isn't working?
💛 
E

**Comment by john-soklaski** [comment]
@emmalou11 

I think the most straightforward way to do this is to style the ul and li based on the parent element.
Right now the parent element of the menu is a <div> tag:

```
           <div>
                <ul>
                    <li><a href="/aboutme.html">about me</a></li>
                    <li><a href="/howicanhelp.html">how i can help</a></li>
                    <li><a href="/contactme.html">contact me</a></li>
                </ul>
            </div>
```

Instead of <div>, there is a more semantically specific [<nav>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav) tag  that we can use instead (used to indicate the navigation portion of the page).

Now, in the css file, you can make the style rules for ul and li to be more specific:

```
nav ul {
    text-align: center;
    padding-left: 0;
}

nav li {
    display: inline-block;
    margin-left: 1rem;
    margin-right: 1rem;
}
```

**Comment by elmcaleavy** [comment]
Thanks John.  I fixed it.  I think this is the ID for the commit, I think... 
#503afdec
